### ISSUE TITLE
pandana 2.0.0 gcc error during install on linux machine

### ISSUE THREAD

**Issue by sablanchard** [UDST/pandana#51]
I have a linux (4.1.15-8) machine with SUSE (gcc version 4.8.5) and python 2.7.11 with anaconda 4.0.0 64-bit and under a variety of scenarios I can not get pandana 2.0.0 to install properly. All except for conda seem to all be a gcc error. Could it be a gcc path issue? Any thoughts on how to get around this or any plans to release 2.0.0 via conda? 

**1) conda install pandana**
After adding the correct channel, only version 0.1.2 is available via conda. Version 0.1.2 installs fine this way.

**2) pip install pandana (for pandana 2.0.0)**
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/sablanchard/anaconda2/lib/python2.7/site-packages/numpy/core/include -I. -Isrc/ann_1.1.2/include -I/home/sablanchard/anaconda2/include/python2.7 -c src/accessibility.cpp -o build/temp.linux-x86_64-2.7/src/accessibility.o -w -std=c++0x -O3 -fpic -g -fopenmp
    unable to execute 'gcc': No such file or directory
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/sablanchard/anaconda2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-veqtsZ/pandana/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-yCejEP-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-veqtsZ/pandana/

**3) install via the repo clone for 2.0.0 with python setup.py install**
building 'pandana._pyaccess' extension
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/sablanchard/anaconda2/lib/python2.7/site-packages/numpy/core/include -I. -Isrc/ann_1.1.2/include -I/home/sablanchard/anaconda2/include/python2.7 -c src/accessibility.cpp -o build/temp.linux-x86_64-2.7/src/accessibility.o -w -std=c++0x -O3 -fpic -g -fopenmp
unable to execute 'gcc': No such file or directory
error: command 'gcc' failed with exit status 1

This all stems from an error in 0.1.2 with get_node_ids that I am assuming is fixed in 2.0.0 because this same data with the same command on another machine with 2.0.0 works fine:

**blocks['node_id'] = net.get_node_ids(blocks['x'], blocks['y'])**

KeyError                                  Traceback (most recent call last)
<ipython-input-5-d02da4cfb8aa> in <module>()
      1 t0 = time.time()
----> 2 blocks['node_id'] = net.get_node_ids(blocks['x'], blocks['y'])
      3 print int(time.time()-t0), 'sec.' #

/home/sablanchard/anaconda2/lib/python2.7/site-packages/pandana-0.1.2-py2.7-linux-x86_64.egg/pandana/network.pyc in get_node_ids(self, x_col, y_col, mapping_distance)
    342         # later date - need to convert from internal to external ids
    343         node_ids = pd.Series(self.nodes_df.reset_index().
--> 344                              iloc[s]["index"].values,
    345                              index=s.index)
    346         return node_ids

/home/sablanchard/anaconda2/lib/python2.7/site-packages/pandas/core/frame.pyc in __getitem__(self, key)
   1990             return self._getitem_multilevel(key)
   1991         else:
-> 1992             return self._getitem_column(key)
   1993 
   1994     def _getitem_column(self, key):

/home/sablanchard/anaconda2/lib/python2.7/site-packages/pandas/core/frame.pyc in _getitem_column(self, key)
   1997         # get column
   1998         if self.columns.is_unique:
-> 1999             return self._get_item_cache(key)
   2000 
   2001         # duplicate columns & possible reduce dimensionality

/home/sablanchard/anaconda2/lib/python2.7/site-packages/pandas/core/generic.pyc in _get_item_cache(self, item)
   1343         res = cache.get(item)
   1344         if res is None:
-> 1345             values = self._data.get(item)
   1346             res = self._box_item_values(item, values)
   1347             cache[item] = res

/home/sablanchard/anaconda2/lib/python2.7/site-packages/pandas/core/internals.pyc in get(self, item, fastpath)
   3223 
   3224             if not isnull(item):
-> 3225                 loc = self.items.get_loc(item)
   3226             else:
   3227                 indexer = np.arange(len(self.items))[isnull(self.items)]

/home/sablanchard/anaconda2/lib/python2.7/site-packages/pandas/indexes/base.pyc in get_loc(self, key, method, tolerance)
   1876                 return self._engine.get_loc(key)
   1877             except KeyError:
-> 1878                 return self._engine.get_loc(self._maybe_cast_indexer(key))
   1879 
   1880         indexer = self.get_indexer([key], method=method, tolerance=tolerance)

pandas/index.pyx in pandas.index.IndexEngine.get_loc (pandas/index.c:4027)()
pandas/index.pyx in pandas.index.IndexEngine.get_loc (pandas/index.c:3891)()
pandas/hashtable.pyx in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12408)()
pandas/hashtable.pyx in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12359)()
KeyError: 'index'

**Comment by fzenoni** [comment]
Hi all, 

Was this ever solved?
I am on Ubuntu 16.04.4 LTS, gcc version 5.4.0. I managed to install pandana by doing `pip2.7 install -U pandana` (using `pip` gave an error as it was using by default python3). But then I am unable to do `import pandana` in a python session.
Here's the log:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fzenoni/.local/lib/python2.7/site-packages/pandana/__init__.py", line 1, in <module>
    from network import Network
  File "/home/fzenoni/.local/lib/python2.7/site-packages/pandana/network.py", line 10, in <module>
    from . import _pyaccess
ImportError: /home/fzenoni/.local/lib/python2.7/site-packages/pandana/_pyaccess.so: undefined symbol: GOMP_parallel`

**Comment by Eh2406** [comment]
@pksohn I know you have been doing a lot of work on our releases infrastructure. Is this still broken?

**Comment by pksohn** [comment]
This should be fixed now that latest is out on Conda. @sablanchard?

**Comment by sablanchard** [comment]
@pksohn I no longer have access to the machine that had that particular environment, the latest Pandana installs fine on linux on other machines so I am unable to test the particulars of this issue again unless I try to duplicate the environment which still may not replicate it fully. I am more curious about @fzenoni issue here, do you still experience this error on the latest release?

**Comment by jucajuca** [comment]
I'm having a similar issue here:

ubuntu 16.04 LTS 
installed pandana with: pip install -U pandana

when I try to import pandana I get the following error:

```
Traceback (most recent call last):
  File "simple_example.py", line 23, in <module>
    import pandana.network as pdna
  File "build/bdist.linux-x86_64/egg/pandana/__init__.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/pandana/network.py", line 10, in <module>
  File "build/bdist.linux-x86_64/egg/pandana/_pyaccess.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/pandana/_pyaccess.py", line 6, in __bootstrap__
ImportError: /home/jccb/.cache/Python-Eggs/pandana-0.3.0-py2.7-linux-x86_64.egg-tmp/pandana/_pyaccess.so: undefined symbol: GOMP_parallel
```

Also installed conda gcc:

```
$ conda install -y gcc
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /media/shared/anaconda2/anaconda2:

The following NEW packages will be INSTALLED:

    cloog: 0.18.0-0     
    gcc:   4.8.5-7      
    gmp:   6.1.0-0      
    isl:   0.12.2-0     
    mpc:   1.0.3-0      
    mpfr:  3.1.5-0      

The following packages will be UPDATED:

    conda: 4.3.16-py27_0 --> 4.3.21-py27_0
```

**Comment by jucajuca** [comment]
Solved it by completely removing anaconda and reinstalling everything from scratch. I think the problem was that I din't use the conda-forge channel

**Comment by fzenoni** [comment]
Sorry about the delay. I reinstalled Pandana using the simple command `pip2.7 install -U pandana`. I did not manually reinstall anything else (some other package was automatically included in the installation process) . Eventually, the `import pandana` did not give any error!
This is as far as I went, so I have no idea if bugs are still living elsewhere, but this is a major improvement.

Thank you very much.
